//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogTag
    {
        public decimal ID { get; set; }
        public decimal BlogID { get; set; }
        public decimal TagID { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
