//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public Blog()
        {
            this.BlogLikes = new HashSet<BlogLike>();
            this.BlogTags = new HashSet<BlogTag>();
            this.Comments = new HashSet<Comment>();
            this.BlogCategories = new HashSet<BlogCategory>();
        }
    
        public decimal ID { get; set; }
        public decimal UserID { get; set; }
        public string Title { get; set; }
        public string Post { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ApprovalDate { get; set; }
        public decimal NumViews { get; set; }
        public decimal NumShares { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<bool> AllowComments { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<BlogLike> BlogLikes { get; set; }
        public virtual ICollection<BlogTag> BlogTags { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<BlogCategory> BlogCategories { get; set; }
    }
}
