//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public Comment()
        {
            this.CommentLikes = new HashSet<CommentLike>();
        }
    
        public int ID { get; set; }
        public int UserID { get; set; }
        public int BlogID { get; set; }
        public string Post { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CommentLike> CommentLikes { get; set; }
    }
}
